project_name: outdated
release:
  github:
    owner: replicatedhq
    name: outdated
builds:
  - id: outdated
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    - arm64
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/outdated/main.go
    ldflags: -s -w
      -X github.com/replicatedhq/outdated/pkg/version.version={{.Version}}
      -X github.com/replicatedhq/outdated/pkg/version.gitSHA={{.Commit}}
      -X github.com/replicatedhq/outdated/pkg/version.buildTime={{.Date}}
      -extldflags "-static"
    flags: -tags netgo -installsuffix netgo
    binary: outdated
    hooks: {}
archives:
  - id: outdated
    builds:
      - outdated
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*
