apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: community-images
spec:
  version: {{ .TagName }}
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/dims/community-images/releases/download/{{ .TagName }}/community-images_linux_amd64.tar.gz" .TagName }}
    files:
    - from: community-images
      to: .
    - from: LICENSE
      to: .
    bin: community-images
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/dims/community-images/releases/download/{{ .TagName }}/community-images_linux_arm64.tar.gz" .TagName }}
    files:
    - from: community-images
      to: .
    - from: LICENSE
      to: .
    bin: community-images
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/dims/community-images/releases/download/{{ .TagName }}/community-images_darwin_amd64.tar.gz" .TagName }}
    files:
    - from: community-images
      to: .
    - from: LICENSE
      to: .
    bin: community-images
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/dims/community-images/releases/download/{{ .TagName }}/community-images_darwin_arm64.tar.gz" .TagName }}
    files:
    - from: community-images
      to: .
    - from: LICENSE
      to: .
    bin: community-images
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/dims/community-images/releases/download/{{ .TagName }}/community-images_windows_amd64.zip" .TagName }}
    files:
    - from: community-images.exe
      to: .
    - from: LICENSE
      to: .
    bin: community-images.exe
  shortDescription: Finds community-images container images running in a cluster
  homepage: https://github.com/dims/community-images
  description: |
    The plugin will scan for all pods in all namespaces that you have at least
    read access to. It will then connect to the registry that hosts the image,
    and (if there's permission), it will analyze your tag to the list of
    current tags.

    The output is a list of all images, with the most out-of-date images in red,
    slightly outdated in yellow, and up-to-date in green.

    For additional options:
      $ kubectl community-images --help
      or https://github.com/dims/community-images/blob/master/doc/USAGE.md
