name: snapshot-release

on:
  push:
    branches:
      - master
  
jobs:
  create-snapshot-release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Create a snapshot release
      run: make snapshot-release

